package com.karim.posts.data.mapper

import com.karim.posts.data.local.entity.PostEntity
import com.karim.posts.data.remote.model.PostDTO
import com.karim.posts.domain.model.Post
import org.junit.Test
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull

class PostMapperTest {

    @Test
    fun `toPost should map PostEntity to Post correctly`() {
        // Given
        val postEntity = PostEntity(
            id = 1,
            title = "Test Title",
            imageUrl = "https://example.com/image.jpg"
        )

        // When
        val result = postEntity.toPost()

        // Then
        assertEquals(1, result.id)
        assertEquals("Test Title", result.title)
        assertEquals("https://example.com/image.jpg", result.imageUrl)
    }

    @Test
    fun `toPostEntity should map PostDTO to PostEntity correctly`() {
        // Given
        val postDTO = PostDTO(
            title = "Test Title",
            imageUrl = "https://example.com/image.jpg"
        )

        // When
        val result = postDTO.toPostEntity()

        // Then
        assertEquals("Test Title", result.title)
        assertEquals("https://example.com/image.jpg", result.imageUrl)
        // Note: id will be auto-generated by Room, so we don't assert it
    }

    @Test
    fun `toPost should handle empty strings`() {
        // Given
        val postEntity = PostEntity(
            id = 0,
            title = "",
            imageUrl = ""
        )

        // When
        val result = postEntity.toPost()

        // Then
        assertEquals("", result.title)
        assertEquals("", result.imageUrl)
    }

    @Test
    fun `toPostEntity should handle long strings`() {
        // Given
        val longTitle = "A".repeat(1000)
        val longUrl = "https://example.com/" + "a".repeat(1000) + ".jpg"
        val postDTO = PostDTO(
            title = longTitle,
            imageUrl = longUrl
        )

        // When
        val result = postDTO.toPostEntity()

        // Then
        assertEquals(longTitle, result.title)
        assertEquals(longUrl, result.imageUrl)
    }
}

